name: Python build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Install Apahce
        run: choco install apache-httpd --force --params '/noService /installLocation:${{ github.workspace }}\Apache24'

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build APXS
        working-directory: ${{ github.workspace }}/apxs
        run: perl -I. Configure.pl --with-apache2=${{ github.workspace }}/Apache24 --with-apache-prog=httpd.exe

      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Build mod_python
        run: |
          ./configure --with-apxs ${{ github.workspace }}\apxs_win32
          make
          make install
